apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
  namespace: whfun
  labels:
    hello: "true"
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2 
  template:
    metadata:
      labels:
        hello: "true"
        app: nginx
    spec:
      containers:
      - name: nginx
        image: quay.io/bitnami/nginx:latest
        ports:
        - containerPort: 80
