apiVersion: v1
kind: Namespace
metadata:
  name: whfun

---

apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: hello-webhook
  namespace: whfun
  annotations:
    cert-manager.io/inject-ca-from: whfun/hello-webhook
webhooks:
- name: hello-webhook.what.fun
  objectSelector:
    matchLabels:    
      hello: "true"
  rules:
  - apiGroups:   [""]
    apiVersions: ["v1"]
    operations:  ["CREATE"]
    resources:   ["pods"]
    scope:       "Namespaced"
  clientConfig:
    service:
      namespace: whfun
      name: hello-webhook
      path: /mutate
  admissionReviewVersions: ["v1", "v1beta1"]
  sideEffects: None
  timeoutSeconds: 10

---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hello-webhook
  namespace: whfun
spec:
  secretName: hello-webhook
  dnsNames:
  - "hello-webhook.whfun.svc"
  issuerRef:
    name: selfsigned

---

apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned
  namespace: whfun
spec:
  selfSigned: {}
